services:
  - type: static
    name: mangadak-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
