version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: django-backend-web
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app          # chỉ code app
      - ./backend/media:/app/media      # cho media
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: typescript-frontend-web
    ports:
      - "5174:5174"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    stdin_open: true
    command: ["npm", "run", "dev"]

