# Generated by Django 4.2.20 on 2025-04-02 14:25

import chapter.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manga', '0002_delete_chapters'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaChapter',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(default='Chương mới', max_length=255)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga')),
            ],
        ),
        migrations.CreateModel(
            name='MangaChapterImage',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(default='', upload_to=chapter.models.chapter_image_upload_path)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chapter.mangachapter')),
            ],
        ),
    ]
