# Generated by Django 4.2.20 on 2025-04-02 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mangachapter',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
