# Generated by Django 4.2.20 on 2025-06-01 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('novel', '0001_initial'),
        ('manga', '0001_initial'),
        ('chapter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelchapter',
            name='novel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.novel'),
        ),
        migrations.AddField(
            model_name='mangachapterimage',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chapter.mangachapter'),
        ),
        migrations.AddField(
            model_name='mangachapter',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga'),
        ),
    ]
