# Generated by Django 4.2.20 on 2025-04-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0002_mangachapter_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapter',
            name='number',
        ),
    ]
