# Generated by Django 4.2.20 on 2025-04-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chapter', '0003_remove_mangachapter_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mangachapter',
            name='views',
        ),
    ]
