# Generated by Django 4.2.20 on 2025-04-04 09:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('novel', '0001_initial'),
        ('chapter', '0004_remove_mangachapter_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='NovelChapter',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='Chương mới', max_length=255)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('novel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='novel.novel')),
            ],
        ),
    ]
