# Generated by Django 4.2.20 on 2025-03-28 02:12
 
from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]