# Generated by Django 4.2.20 on 2025-03-28 02:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0002_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
