# Generated by Django 4.2.20 on 2025-03-28 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0003_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Genres',
            new_name='Genre',
        ),
    ]
