# Generated by Django 4.2.20 on 2025-04-01 15:11

from django.db import migrations

from ..import_data import create_genres
class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0004_rename_genres_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='description',
        ),
        migrations.RunPython(create_genres),
    ]
