# Generated by Django 4.2.20 on 2025-04-14 14:05
from django.db import migrations, models
from ..import_data import create_genres
class Migration(migrations.Migration):

    dependencies = [
        ('genres', '0005_remove_genre_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='isCommon',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(create_genres),
    ]
