# Generated by Django 4.2.20 on 2025-04-01 19:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0005_remove_genre_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cover_image', models.ImageField(blank=True, default='manga_covers/default.jpg', upload_to='manga_covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='Không rõ', max_length=255)),
                ('numComments', models.IntegerField(blank=True, default=0, null=True)),
                ('numViews', models.IntegerField(blank=True, default=0, null=True)),
                ('numFavorites', models.IntegerField(blank=True, default=0, null=True)),
                ('numChapters', models.IntegerField(blank=True, default=0, null=True)),
                ('numRatings', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('completed', 'Hoàn thành'), ('ongoing', 'Còn tiếp'), ('paused', 'Tạm ngưng'), ('unverified', 'Chưa xác minh')], default='unverified', max_length=20)),
                ('genres', models.ManyToManyField(blank=True, related_name='manga_genres', to='genres.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='manga.manga')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('chapter_number', models.IntegerField(blank=True, null=True)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='manga.manga')),
            ],
        ),
    ]
