# Generated by Django 4.2.20 on 2025-04-02 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Chapters',
        ),
    ]
