# Generated by Django 4.2.20 on 2025-04-04 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_delete_chapters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manga',
            old_name='numRatings',
            new_name='numLikes',
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
