# Generated by Django 4.2.20 on 2025-03-09 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0002_alter_manga_cover_image_chapter_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='cover_image',
            field=models.ImageField(blank=True, default='manga_covers/default.jpg', upload_to='manga_covers/'),
        ),
    ]
