# Generated by Django 4.2.20 on 2025-03-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0003_alter_manga_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
