# Generated by Django 4.2.20 on 2025-05-25 07:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manga', '0003_rename_numratings_manga_numlikes_delete_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='uploader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
