# Generated by Django 4.2.20 on 2025-05-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0004_manga_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='numChapters',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='numComments',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='numFavorites',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='numLikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='manga',
            name='numViews',
            field=models.IntegerField(default=0),
        ),
    ]
