# Generated by Django 4.2.20 on 2025-05-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default.jpg', null=True, upload_to='covers/'),
        ),
    ]
