# Generated by Django 4.2.20 on 2025-04-04 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='manga',
        ),
        migrations.AddField(
            model_name='favorite',
            name='story_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='favorite',
            name='type',
            field=models.CharField(choices=[('novel', 'Tiểu thuyết'), ('manga', 'Manga'), ('audio', 'Audio'), ('forum', 'Diễn đàn')], default='novel', max_length=20),
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('story_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('novel', 'Tiểu thuyết'), ('manga', 'Manga'), ('audio', 'Audio'), ('forum', 'Diễn đàn')], default='novel', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('post_id', models.CharField(blank=True, max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('novel', 'Tiểu thuyết'), ('manga', 'Manga'), ('audio', 'Audio'), ('forum', 'Diễn đàn')], default='novel', max_length=20)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='users.comments')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
