# Generated by Django 4.2.20 on 2025-05-30 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='chapter_object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comments',
            name='object_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
