# Generated by Django 4.2.20 on 2025-05-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_comments_chapter_object_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cover',
            field=models.ImageField(default='covers/default.jpg', upload_to='user_covers/'),
        ),
    ]
