# Generated by Django 4.2.20 on 2025-06-01 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='chapter_content_type',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='chapter_object_id',
        ),
    ]
